# Generated by Django 4.1.4 on 2022-12-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phonenumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('selectcourse', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('Selenium', 'Selinium'), ('Django', 'Django')], max_length=10)),
                ('modeloftrining', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20)),
            ],
        ),
    ]
