# Generated by Django 4.1.4 on 2022-12-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Washing_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('amount', models.FloatField(max_length=256)),
            ],
        ),
    ]
